import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# ============================================================
# Geometric Lift from S¹ to S²
# Residual Efolding Polar Embedding of the Cosmological Clock
# ============================================================

# Arcan(τ) / Cosmological Clock constants
psi = 0.1503378808
delta = 7 * psi - np.pi / 3          # residual seed ≈ 0.0051676144
print(f"Residual δ = {delta:.10f} rad")

# Parametric embedding
# θ(λ) = π λ
# ϕ_wind(λ, n) = 2π (1 - λ) + n δ

def polar_embedding(lambda_vals, n=0, delta=delta):
    """Return (x, y, z) on the unit sphere for given λ and cycle index n."""
    theta = np.pi * lambda_vals
    phi   = 2 * np.pi * (1 - lambda_vals) + n * delta
    x = np.sin(theta) * np.cos(phi)
    y = np.sin(theta) * np.sin(phi)
    z = np.cos(theta)
    return x, y, z

# Create figure
fig = plt.figure(figsize=(14, 11))
ax = fig.add_subplot(111, projection='3d')

# Unit sphere wireframe (light)
u = np.linspace(0, 2 * np.pi, 60)
v = np.linspace(0, np.pi, 30)
x_s = np.outer(np.cos(u), np.sin(v))
y_s = np.outer(np.sin(u), np.sin(v))
z_s = np.outer(np.ones_like(u), np.cos(v))
ax.plot_surface(x_s, y_s, z_s, color='royalblue', alpha=0.08, edgecolor='none')
ax.plot_wireframe(x_s, y_s, z_s, color='steelblue', alpha=0.15, linewidth=0.3)

# Equator
eq = np.linspace(0, 2 * np.pi, 100)
ax.plot(np.cos(eq), np.sin(eq), 0, 'b-', lw=1.8, alpha=0.7, label='Equator (θ = π/2)')

# Plot several residual cycles (n = 0, 1, 2, 3)
colors = ['crimson', 'darkorange', 'green', 'purple']
lambda_dense = np.linspace(0, 1, 400)

for n, color in enumerate(colors):
    x, y, z = polar_embedding(lambda_dense, n=n)
    ax.plot(x, y, z, color=color, lw=2.2, alpha=0.9,
            label=f'Cycle n={n}  (offset = {n}δ)')

# Mark key points on the n=0 spiral
key_lambdas = [0.0, 0.25, 0.5, 0.75, 1.0]
x_key, y_key, z_key = polar_embedding(np.array(key_lambdas), n=0)
ax.scatter(x_key, y_key, z_key, color='black', s=40, zorder=10)
for i, lam in enumerate(key_lambdas):
    ax.text(x_key[i]*1.12, y_key[i]*1.12, z_key[i]*1.12,
            f'λ={lam:.2f}', fontsize=8, ha='center')

# North & South poles
ax.scatter([0], [0], [1], color='navy', s=80, label='North Pole (λ=0)')
ax.scatter([0], [0], [-1], color='darkred', s=80, label='South Pole (λ=1)')

# Axes indicators
ax.plot([-1.3, 1.3], [0, 0], [0, 0], 'r-', lw=1.5, alpha=0.6)   # X
ax.plot([0, 0], [-1.3, 1.3], [0, 0], color='darkorange', lw=1.5, alpha=0.6)  # Y
ax.plot([0, 0], [0, 0], [-1.3, 1.3], 'purple', lw=1.5, alpha=0.6)  # Z

ax.text(1.4, 0, 0, 'X (LENGTH)', color='red', fontsize=9)
ax.text(0, 1.4, 0, 'Y (WIDTH)', color='darkorange', fontsize=9)
ax.text(0, 0, 1.4, 'Z (HEIGHT)', color='purple', fontsize=9)

# Title and labels
ax.set_title("Geometric Lift from $S^1$ to $S^2$\n"
             r"Residual Efolding: $\theta(\lambda)=\pi\lambda$,  "
             r"$\phi_{\rm wind}(\lambda,n)=2\pi(1-\lambda)+n\delta$"
             "\nCosmological Clock – Arcan(τ) Family",
             fontsize=13, fontweight='bold', pad=12)

ax.set_xlim(-1.5, 1.5)
ax.set_ylim(-1.5, 1.5)
ax.set_zlim(-1.5, 1.5)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.view_init(elev=22, azim=35)
ax.legend(loc='upper left', fontsize=8, framealpha=0.92)

# Info box
info = (
    f"δ (residual) ≈ {delta:.8f} rad\n"
    r"θ(λ) = πλ          (polar angle)" "\n"
    r"ϕ_wind = 2π(1-λ) + nδ   (azimuth)" "\n"
    "λ ∈ [0,1]  •  n = cycle index\n"
    "Adiabatic cooling + 360° spherical recycle\n"
    "Comoving topology generated by residual efolding"
)
fig.text(0.02, 0.02, info, fontsize=9, family='monospace',
         bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.95),
         verticalalignment='bottom')

plt.tight_layout(rect=[0, 0.12, 1, 0.97])
plt.savefig('geometric_lift_S1_to_S2.png', dpi=160, bbox_inches='tight', facecolor='white')
plt.show()
